services:
  postgres:
    image: postgres:15
    container_name: finanzas-dash
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finanzas_admin
      POSTGRES_PASSWORD: esto_es_un_secreto
      POSTGRES_DB: finanzas
    volumes:
      - bd_finanzas:/var/lib/postgresql/data

volumes:
  bd_finanzas: