name: Deploy to Home Server

on:
  push:
    branches: 
      - release/testing
      - IntegracionServerLocal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-ci


      - name: Debug key length
        run: echo "SSH_KEY length=${#SSH_KEY}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
           host: ${{ secrets.SERVER_IP }}
           username: servertanuko
           key: ${{ secrets.SSH_KEY }}
           port: 22
           timeout: 60s
           command_timeout: 30m
           request_pty: true
           script: |
            echo "SSH OK"
            cd /home/deploys/Proyectos/Finanzas-Dashboard
            git pull
            docker compose up -d --build
