name: Deploy to Home Server

on:
  push:
    branches: 
      - release/testing
      - IntegracionServerLocal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-ci


      - name: Debug key length
        run: echo "SSH_KEY length=${#SSH_KEY}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      
      - name: SSH Deploy (native)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh -o StrictHostKeyChecking=no \
          servertanuko@${{ secrets.SERVER_IP }} \
          "echo SSH OK"
            
